name: Deploy MAIN

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    concurrency:
      group: deploy-main
      cancel-in-progress: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create CNAME
        run: echo "demo.h2houseofhealth.com" > ./CNAME

      - name: Deploy to gh-pages-main
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages-main
          publish_dir: .
